services:
  - type: web
    name: stayFinder-backend
    runtime: docker
    plan: free
    dockerfilePath: stayFinder-backend/Dockerfile
    dockerContext: stayFinder-backend
    healthCheckPath: /api/hotels/search
    envVars:
      - key: PORT
        value: 10000
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_JPA_HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: false
      - key: APP_JWT_EXPIRATION
        value: 86400000
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
      - key: APP_JWT_SECRET
        sync: false
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
